language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run
before_script:
  - docker --version # Print the version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend

  # Tags
  - docker tag udagram-api-feed 0xceejay/udagram-api-feed:v1
  - docker tag udagram-api-user 0xceejay/udagram-api-user:v1
  - docker tag udagram-reverseproxy 0xceejay/udagram-reverseproxy:v1
  - docker tag udagram-frontend 0xceejay/udagram-frontend:local

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 0xceejay/udagram-reverserproxy:v1
  - docker push 0xceejay/udagram-frontend:local
  - docker push 0xceejay/udagram-api-user:v1
  - docker push 0xceejay/udagram-api-feed:v1