name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./udagram-api-feed/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/udagram-api-feed:latest
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./udagram-api-user/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/udagram-api-user:latest
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./udagram-reverseproxy/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/udagram-reverseproxy:latest
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./udagram-frontend/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/udagram-frontend:local
